name: MAIN Pack

on:
  workflow_dispatch:

concurrency:
  group: main-pack
  cancel-in-progress: true

jobs:
  build:
    name: Build MAIN Pack
    runs-on: ubuntu-latest
    outputs:
      NEXT_VERSION: ${{ steps.get_version.outputs.next_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Precompute event number and MAIN version
        id: get_version
        run: |
          MAIN_VERSION=$(grep 'MAIN:' packVersion.txt | awk '{print $2}')
          NEXT_VERSION=$((MAIN_VERSION + 1))
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "EVENT_NUM=$EVENT_NUM" >> $GITHUB_OUTPUT

      - name: Create MAIN ZIP
        run: |
          rm -f IBL-main.zip
          cd mainPack
          zip -r ../IBL-main.zip . -x ".git/*" ".github/*"
          cd ..

      - name: Compute SHA-1 hash and save as artifact
        run: |
          SHA1=$(sha1sum IBL-main.zip | awk '{ print $1 }')
          echo "$SHA1" > ibl-main.hash

      - name: Upload MAIN ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mainLatest
          files: IBL-main.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload hash artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-hash
          path: ibl-main.hash

  update-version-and-hash:
    name: Update MAIN Version and Hash
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download hash artifact
        uses: actions/download-artifact@v4
        with:
          name: main-hash
          path: .

      - name: Update MAIN version and hash in root file
        run: |
          git pull origin main
          SHA1=$(cat ibl-main.hash)
          NEXT_VERSION=${{ needs.build.outputs.NEXT_VERSION }}
          sed -i "s/^[[:space:]]*MAIN:.*/    MAIN: $NEXT_VERSION/" packVersion.txt
          sed -i "s/^[[:space:]]*MAIN_HASH:.*/    MAIN_HASH: $SHA1/" packVersion.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packVersion.txt
          git commit -m "Increment MAIN version to $NEXT_VERSION and update hash"
          git push origin main
